apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  labels: 
    app: go-app
spec:
  type: NodePort
  selector:
    app: go-app
  ports:
    - port: 80

      targetPort: 8080
      
      